---
title: "R Notebook 2"
output:
  html_document: default
  html_notebook: default
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE}
library(tidyverse)
library(ggplot2)
library(plotly)
library(gridExtra)
data = read.csv('edge1.1.csv')
```


```{r}
p = ggplot(data,
           aes(x=Male_Contributions,
               y=Female_Contributions)) 
p + geom_point() + facet_wrap(~Discipline)
```

```{r,fig.height=6}
df = data
df$mine = as.integer(as.character(df$PhD_Year))
p = ggplot(df %>% filter(mine != 'NA'),
           aes(x=Male_Contributions,
               y=Female_Contributions)) 
p + geom_point() + facet_wrap(~PhD_Year)
```


```{r}
plotRank = function(GROUP){
  x.string=GROUP
  df = data %>%
    group_by_(GROUP) %>%
    summarise(n = n()) %>%
    arrange(-n) %>%
    top_n(20)
  p = ggplot(df,aes_string(x=x.string,y='n'))
  p + geom_bar(stat='identity') + coord_flip()
}

plotRank('Title')
plotRank('Department')
plotRank('Id')
plotRank('PhD_Institution')
plotRank('PhD_Field')
plotRank('PhD_Year')
plotRank('Discipline')
plotRank('HavePhD')
```


```{r}
plotScatter = function(GROUP){
  tmp = data %>% 
  group_by_("ThreadId",GROUP) %>%
  summarise(Female_Contributions = sum(Female_Contributions),
            FemaleParticipation = min(FemaleParticipation),
            UniqueFemaleContributors = sum(UniqueFemaleContributors),
            UniqueFemaleParticipation = min(UniqueFemaleParticipation))

  p1 = ggplot(tmp,aes(x=FemaleParticipation,y=Female_Contributions)) + geom_point(aes_string(col=GROUP))
  p2 = ggplot(tmp,aes(x=FemaleParticipation,y=UniqueFemaleContributors)) + geom_point(aes_string(col=GROUP))
  p3 = ggplot(tmp,aes(x=UniqueFemaleParticipation,y=Female_Contributions)) + geom_point(aes_string(col=GROUP))
  p4 = ggplot(tmp,aes(x=UniqueFemaleParticipation,y=UniqueFemaleContributors)) + geom_point(aes_string(col=GROUP))
  
  grid.arrange(p1,p2,p3,p4,ncol=2)
}

plotScatter('Discipline')

```

